### PR TITLE
Add sample files for config flow

### PR DESCRIPTION
**Pull request by omriasta**
This is extremely first draft and definitely does not work as you will need to finish the rest of the tests in config_flow.py and then modify __init__.py to match it. The only work I did was to setup the form to input parameters (user, pass, prefer cache and the 2 timeout values). I did not setup the storage of config entries or the authentication process to validate the credentials.

### CODE REVIEW

**Comment by omriasta** [comment]
I was able to get a working config flow. It's pretty shaky, and doesn't give errors if the device can't be contacted but it is working. Not sure if you want me to create a new PR or update this one. I have the code here https://github.com/omriasta/hass-kumo/tree/configflow

**Comment by dlarrick** [comment]
Hey, that's great!
I *may* have a chance to look at it this weekend ... no promises.
It doesn't matter to me if it's a new or updated PR, but you will need to resolve conflicts (update your branch to be based off latest master) either way.

**Comment by omriasta** [comment]
Yep, I'll clean it up a bit since there is a lot of commented out junk and I can probably look more into adding all the required unload methods....

**Comment by omriasta** [comment]
Closing since have working version

**Pull request closed without merging**
