### PR TITLE
Use `Platform.CLIMATE` / `Platform.SENSOR` instead of 'domain' constants

### PR DESCRIPTION
**Pull request by mxr**
This is a minor cleanup with no change in functionality but it avoids using "domain" strings in place of "platform" strings

### CODE REVIEW

**Comment by dlarrick** [comment]
When did this become available? Does the [minimum HA version](https://github.com/dlarrick/hass-kumo/blob/master/custom_components/kumo/manifest.json#L11) need to be changed?

**Comment by mxr** [comment]
From what I can tell the new constants were introduced in 2021 so we don't have to increase the version. Is that right?

https://github.com/mxr/core/commit/707fe67c0053af7c3955077fabd2734633c03ecd#diff-07e20eb7c6560330f9774eb23343f5dd3002106bb8b6523ccb18d95857990d77R22-R54

**Comment by dlarrick** [comment]
Ah OK, thanks. I'm not going to make a new release for just this change, but I'm merging it now and it'll go out whenever we do have something else.

**Review by dlarrick — APPROVED** [review]

**Comment by mxr** [comment]
Makes sense

**Pull request merged**
