### PR TITLE
Fix set_temperature for heat_cool mode

### PR DESCRIPTION
**Pull request by FrancisLab**
Address issues highlighted in https://github.com/dlarrick/hass-kumo/issues/27

* Define new constants for Kumo state strings. Long term it would make sense to define those in pykumo itself and import them like HA contants.
* When using `self.hvac_mode`, convert it to a Kumo string
* When validating `mode_to_set`, validate against set of Kumo strings
* Fix call to set_cool_setpoint in else case

Was able to test on previous versions of hass-kumo, but currently blocked from testing on v0.1.4 due to other issues.

### CODE REVIEW

**Comment by FrancisLab** [comment]
We've figured out the issues blocking me from testing on v.0.1.4. So here we go:

# Test Plan
## Setting Auto-mode temperature
1. Set unit in auto mode
2. Use climate.set_temperature service call to set new target_temp_low & target_temp_high
3. Ensure UI updates to reflect new temperatures within one minute
4. Ensure no error logs in HASS
5. Ensure proper status in Kumo Cloud app

## Setting Head mode temperature
1. Set unit in heat mode
2. Use climate.set_temperature service call to set new temperature
3. Ensure UI updates to reflect new temperature within one minute
4. Ensure no error logs in HASS
5. Ensure proper status in Kumo Cloud app

## Setting Cool mode temperature
1. Same as above with cool mode

## Not setting temperature in other modes
1. Set unit in vent mode
2. Use climate.set_temperature service call to try setting new temperature
3. Ensure no UI updates for a minute
4. Ensure "not setting target temperature for mode" is logged in HASS
5. Ensure proper status in Kumo Cloud app

**Comment by dlarrick** [comment]
I did push 0.1.5 which might make your testing easier / more consistent.

**Comment by FrancisLab** [comment]
I ended up testing everything on 0.1.4. I can do it again on 0.1.5 if you'd like.

**Comment by dlarrick** [comment]
> I ended up testing everything on 0.1.4. I can do it again on 0.1.5 if you'd like.

No that's fine. So we're all good?

**Comment by FrancisLab** [comment]
I went ahead and also tested on 0.1.5! Everything works fine as far as I can tell!

Thanks for fixing the latency issue, it's super responsive now!

**Comment by dlarrick** [comment]
All right, merged and new release pushed. I am going to close the issue now.

**Pull request merged**
